module.exports={
    fileDetailsForContentRecords:"http://hurricane:blizzard@monitortool.newsinc.com/manage/getcontentdetails.php",
    controlRoom:{
        url:"https://administrator:p74e7Ceaa6@control.inform.com/",
        username:"administrator",
        password:"p74e7Ceaa6"
    },
    host:"localhost:4000/",
    manageTool:{
        url:"http://tools.newsinc.com/manage",
        username:"jvallon@newsinc.com",
        password:"Inform.9876"
    }
};